// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAYxcJOfteySX60rfIiINiAh5UIMiHD7o',
    appId: '1:1045319455125:web:5b3524208be3340d50669c',
    messagingSenderId: '1045319455125',
    projectId: 'mi-terra-app',
    authDomain: 'mi-terra-app.firebaseapp.com',
    storageBucket: 'mi-terra-app.appspot.com',
    measurementId: 'G-1EJF472TLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSOgrCukUanWfKyPNH6NGpyueYtgh6VbQ',
    appId: '1:1045319455125:android:ca836a3013072aaa50669c',
    messagingSenderId: '1045319455125',
    projectId: 'mi-terra-app',
    storageBucket: 'mi-terra-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MH_AH9S-3_7G7GRmGlInSmi1X67jD7Y',
    appId: '1:1045319455125:ios:60dc9bf235011e4650669c',
    messagingSenderId: '1045319455125',
    projectId: 'mi-terra-app',
    storageBucket: 'mi-terra-app.appspot.com',
    iosClientId: '1045319455125-q68qr9cscvomp82rlilhbn34cdbtmct5.apps.googleusercontent.com',
    iosBundleId: 'com.example.miTerraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4MH_AH9S-3_7G7GRmGlInSmi1X67jD7Y',
    appId: '1:1045319455125:ios:d0d4b8897b2c307a50669c',
    messagingSenderId: '1045319455125',
    projectId: 'mi-terra-app',
    storageBucket: 'mi-terra-app.appspot.com',
    iosClientId: '1045319455125-1c5djakpmsdajdd4kl6t87hnvj8tvn43.apps.googleusercontent.com',
    iosBundleId: 'com.example.miTerraApp.RunnerTests',
  );
}
